### ISSUE TITLE
Game Crashes when Mobs Die

### ISSUE THREAD

**Issue by LustrousBlue** [TheXFactor117/Loot-Slash-Conquer-Pre1.14#10]
At seemingly random times the game crashes when a mob dies, whether I kill it or not, I know it is this mod, because I tested this with only this mod installed. Please fix this, its annoying to restart Minecraft every other time I kill a zombie. To be clear, I am using the latest version of the mod.

**Comment by TheXFactor117** [comment]
Please send me the crash report - I can't fix it without that.

I was also planning on pushing out a hotfix for some other issues later today, so it'll like get fixed in 0.6.1.1.

**Comment by LustrousBlue** [comment]
I’ll give you the crash report later today the next time it crashes, it also is more frequent in multiplayer, even when mobs aren’t dying in the immediate area

**Comment by LustrousBlue** [comment]
Heres the crash report:

11:43:53 | game | Time: 7/14/18 4:43 PM
-- | -- | --
11:43:53 | game | Description: Ticking entity
11:43:53 | game |  
11:43:53 | game | java.lang.IllegalArgumentException: bound must be positive
11:43:53 | game | at java.util.Random.nextInt(Random.java:388)
11:43:53 | game | at ru.radviger.cases.item.ItemCase.ofRandomType(ItemCase.java:141)
11:43:53 | game | at ru.radviger.cases.Events.onEntityDrops(Events.java:64)
11:43:53 | game | at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_175_Events_onEntityDrops_LivingDropsEvent.invoke(.dynamic)
11:43:53 | game | at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
11:43:53 | game | at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
11:43:53 | game | at net.minecraftforge.common.ForgeHooks.onLivingDrops(ForgeHooks.java:605)
11:43:53 | game | at net.minecraft.entity.EntityLivingBase.func_70645_a(EntityLivingBase.java:1193)
11:43:53 | game | at net.minecraft.entity.monster.EntityZombie.func_70645_a(EntityZombie.java:546)
11:43:53 | game | at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:1014)
11:43:53 | game | at net.minecraft.entity.monster.EntityMob.func_70097_a(EntityMob.java:70)
11:43:53 | game | at net.minecraft.entity.monster.EntityZombie.func_70097_a(EntityZombie.java:233)
11:43:53 | game | at net.minecraft.entity.Entity.func_70030_z(Entity.java:487)
11:43:53 | game | at net.minecraft.entity.EntityLivingBase.func_70030_z(EntityLivingBase.java:224)
11:43:53 | game | at net.minecraft.entity.EntityLiving.func_70030_z(EntityLiving.java:269)
11:43:53 | game | at net.minecraft.entity.Entity.func_70071_h_(Entity.java:388)
11:43:53 | game | at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2087)
11:43:53 | game | at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:377)
11:43:53 | game | at net.minecraft.entity.monster.EntityMob.func_70071_h_(EntityMob.java:50)
11:43:53 | game | at net.minecraft.world.World.func_72866_a(World.java:1990)
11:43:53 | game | at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
11:43:53 | game | at net.minecraft.world.World.func_72870_g(World.java:1952)
11:43:53 | game | at net.minecraft.world.World.func_72939_s(World.java:1756)
11:43:53 | game | at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
11:43:53 | game | at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
11:43:53 | game | at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
11:43:53 | game | at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
11:43:53 | game | at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
11:43:53 | game | at java.lang.Thread.run(Thread.java:745)
11:43:53 | game |  
11:43:53 | game |  
11:43:53 | game | A detailed walkthrough of the error, its code path and all known details is as follows:
11:43:53 | game | ---------------------------------------------------------------------------------------
11:43:53 | game |  
11:43:53 | game | -- Head --
11:43:53 | game | Thread: Client thread
11:43:53 | game | Stacktrace:
11:43:53 | game | at java.util.Random.nextInt(Random.java:388)
11:43:53 | game | at ru.radviger.cases.item.ItemCase.ofRandomType(ItemCase.java:141)
11:43:53 | game | at ru.radviger.cases.Events.onEntityDrops(Events.java:64)
11:43:53 | game | at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_175_Events_onEntityDrops_LivingDropsEvent.invoke(.dynamic)
11:43:53 | game | at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
11:43:53 | game | at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
11:43:53 | game | at net.minecraftforge.common.ForgeHooks.onLivingDrops(ForgeHooks.java:605)
11:43:53 | game | at net.minecraft.entity.EntityLivingBase.func_70645_a(EntityLivingBase.java:1193)
11:43:53 | game | at net.minecraft.entity.monster.EntityZombie.func_70645_a(EntityZombie.java:546)
11:43:53 | game | at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:1014)
11:43:53 | game | at net.minecraft.entity.monster.EntityMob.func_70097_a(EntityMob.java:70)
11:43:53 | game | at net.minecraft.entity.monster.EntityZombie.func_70097_a(EntityZombie.java:233)
11:43:53 | game | at net.minecraft.entity.Entity.func_70030_z(Entity.java:487)
11:43:53 | game | at net.minecraft.entity.EntityLivingBase.func_70030_z(EntityLivingBase.java:224)
11:43:53 | game | at net.minecraft.entity.EntityLiving.func_70030_z(EntityLiving.java:269)
11:43:53 | game | at net.minecraft.entity.Entity.func_70071_h_(Entity.java:388)
11:43:53 | game | at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2087)
11:43:53 | game | at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:377)
11:43:53 | game | at net.minecraft.entity.monster.EntityMob.func_70071_h_(EntityMob.java:50)
11:43:53 | game | at net.minecraft.world.World.func_72866_a(World.java:1990)
11:43:53 | game | at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
11:43:53 | game | at net.minecraft.world.World.func_72870_g(World.java:1952)
11:43:53 | game |  
11:43:53 | game | -- Entity being ticked --
11:43:53 | game | Details:
11:43:53 | game | Entity Type: minecraft:zombie (net.minecraft.entity.monster.EntityZombie)
11:43:53 | game | Entity ID: 164
11:43:53 | game | Entity Name: Zombie
11:43:53 | game | Entity's Exact location: -55.48, 63.00, 175.76
11:43:53 | game | Entity's Block location: World: (-56,63,175), Chunk: (at 8,3,15 in -4,10; contains blocks -64,0,160 to -49,255,175), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
11:43:53 | game | Entity's Momentum: 0.00, -0.08, 0.00
11:43:53 | game | Entity's Passengers: []
11:43:53 | game | Entity's Vehicle: ~~ERROR~~ NullPointerException: null
11:43:53 | game | Stacktrace:
11:43:53 | game | at net.minecraft.world.World.func_72939_s(World.java:1756)
11:43:53 | game | at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
11:43:53 | game |  
11:43:53 | game | -- Affected level --
11:43:53 | game | Details:
11:43:53 | game | Level name: Ocean Man
11:43:53 | game | All players: 2 total; [EntityPlayerMP['epicninja532'/316, l='Ocean Man', x=-574.70, y=62.00, z=-144.45], EntityPlayerMP['coolguy3484'/1115, l='Ocean Man', x=-46.11, y=65.31, z=177.87]]
11:43:53 | game | Chunk stats: ServerChunkCache: 1560 Drop: 0
11:43:53 | game | Level seed: 5436806761580375787
11:43:53 | game | Level generator: ID 06 - rwg, ver 0. Features enabled: true
11:43:53 | game | Level generator options:
11:43:53 | game | Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
11:43:53 | game | Level time: 27480 game time, 27480 day time
11:43:53 | game | Level dimension: 0
11:43:53 | game | Level storage version: 0x04ABD - Anvil
11:43:53 | game | Level weather: Rain time: 23976 (now: false), thunder time: 120467 (now: false)
11:43:53 | game | Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
11:43:53 | game | Stacktrace:
11:43:53 | game | at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
11:43:53 | game | at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
11:43:53 | game | at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
11:43:53 | game | at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
11:43:53 | game | at java.lang.Thread.run(Thread.java:745)
11:43:53 | game |  
11:43:53 | game | -- System Details --
11:43:53 | game | Details:
11:43:53 | game | Minecraft Version: 1.12.2
11:43:53 | game | Operating System: Windows 10 (amd64) version 10.0
11:43:53 | game | Java Version: 1.8.0_51, Oracle Corporation
11:43:53 | game | Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
11:43:53 | game | Memory: 339484184 bytes (323 MB) / 905969664 bytes (864 MB) up to 1073741824 bytes (1024 MB)
11:43:53 | game | JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
11:43:53 | game | IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
11:43:53 | game | FML: MCP 9.42 Powered by Forge 14.23.4.2707 Optifine OptiFine_1.12.2_HD_U_D2 34 mods loaded, 34 mods active
11:43:53 | game | States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
11:43:53 | game |  
11:43:53 | game | \| State     \| ID                 \| Version       \| Source                                      \| Signature                                \|
11:43:53 | game | \|:--------- \|:------------------ \|:------------- \|:------------------------------------------- \|:---------------------------------------- \|
11:43:53 | game | \| UCHIJAAAA \| minecraft          \| 1.12.2        \| minecraft.jar                               \| None                                     \|
11:43:53 | game | \| UCHIJAAAA \| mcp                \| 9.42          \| minecraft.jar                               \| None                                     \|
11:43:53 | game | \| UCHIJAAAA \| FML                \| 8.0.99.99     \| forge-1.12.2-14.23.4.2707.jar               \| e3c3d50c7c986df74c645c0ac54639741c90a557 \|
11:43:53 | game | \| UCHIJAAAA \| forge              \| 14.23.4.2707  \| forge-1.12.2-14.23.4.2707.jar               \| e3c3d50c7c986df74c645c0ac54639741c90a557 \|
11:43:53 | game | \| UCHIJAAAA \| obfuscate          \| 0.2.4         \| minecraft.jar                               \| None                                     \|
11:43:53 | game | \| UCHIJAAAA \| passableleavescore \| 1.0.0         \| minecraft.jar                               \| None                                     \|
11:43:53 | game | \| UCHIJAAAA \| aquaculture        \| 1.6.1         \| Aquaculture-Mod-1.12.2.jar                  \| None                                     \|
11:43:53 | game | \| UCHIJAAAA \| baubles            \| 1.5.2         \| Baubles-Mod-1.12.2.jar                      \| None                                     \|
11:43:53 | game | \| UCHIJAAAA \| micsiege           \| 1.0.2         \| Brutal-Zombie-Siege- Mod-1.12.2.jar         \| None                                     \|
11:43:53 | game | \| UCHIJAAAA \| cases              \| 0.1.0-BETA    \| Cases-Mod-1.12.2.jar                        \| None                                     \|
11:43:53 | game | \| UCHIJAAAA \| scollectibles      \| demo          \| Collectibles-Mod-1.12.2.jar                 \| None                                     \|
11:43:53 | game | \| UCHIJAAAA \| complexcrops       \| v4.0          \| Complex-Crops-Mod-1.12.2.jar                \| None                                     \|
11:43:53 | game | \| UCHIJAAAA \| cosmiclib          \| 0.3.3         \| CosmicLib-1.12.2-0.3.3.ALPHA.jar            \| d3974446c00f9f1d275edce305771eeddf30c658 \|
11:43:53 | game | \| UCHIJAAAA \| culinaryconstruct  \| 1.1.0         \| Culinary-Construct-Mod-1.12.2.jar           \| None                                     \|
11:43:53 | game | \| UCHIJAAAA \| despawningspawners \| 1.1           \| Despawning-Spawners-Mod-1.12.2.jar          \| None                                     \|
11:43:53 | game | \| UCHIJAAAA \| dungeonmobs        \| 5.0.3         \| Dungeon-Mobs-Reborn-Mod-1.12.2.jar          \| None                                     \|
11:43:53 | game | \| UCHIJAAAA \| flora              \| 1.0           \| Flora-and-Fauna-Mod-1.12.2.jar              \| None                                     \|
11:43:53 | game | \| UCHIJAAAA \| geolosys           \| 1.9.4         \| Geolosys-Mod-1.12.2.jar                     \| None                                     \|
11:43:53 | game | \| UCHIJAAAA \| gravestone         \| 1.0.12        \| Gravestone-Mod-1.12.jar                     \| None                                     \|
11:43:53 | game | \| UCHIJAAAA \| jei                \| 4.9.1.168     \| jei_1.12.2-4.9.1.168.jar                    \| None                                     \|
11:43:53 | game | \| UCHIJAAAA \| lsc                \| 0.6.1.2-alpha \| Loot+Slash+Conquer-1.12.2-0.6.1.2-alpha.jar \| None                                     \|
11:43:53 | game | \| UCHIJAAAA \| mantle             \| 1.12-1.3.2.24 \| Mantle-Mod-1.12.2.jar                       \| None                                     \|
11:43:53 | game | \| UCHIJAAAA \| odioitamod         \| 1.3.0         \| Odioita-Mod-1.12.2.jar                      \| None                                     \|
11:43:53 | game | \| UCHIJAAAA \| psf                \| 0.1.0-dev     \| Practical-Space-Fireworks-Mod-1.12.2.jar    \| None                                     \|
11:43:53 | game | \| UCHIJAAAA \| prefab             \| 1.3.0.11      \| Prefab-Mod-1.12.1.jar                       \| None                                     \|
11:43:53 | game | \| UCHIJAAAA \| rwg                \| 1.0.1         \| Realistic-World-Generation-Mod-1.12.2.jar   \| None                                     \|
11:43:53 | game | \| UCHIJAAAA \| ruins              \| 16.9          \| Ruins-Mod-1.12.jar                          \| None                                     \|
11:43:53 | game | \| UCHIJAAAA \| securitycraft      \| v1.8.4.1      \| SecurityCraft-Mod-1.12.2.jar                \| None                                     \|
11:43:53 | game | \| UCHIJAAAA \| simpledivegear     \| 1.0.1         \| Simple-Diving-Gear-Mod-1.12.2.jar           \| None                                     \|
11:43:53 | game | \| UCHIJAAAA \| tickratechanger    \| 1.0.14        \| TickrateChanger-Mod-1.12.2.jar              \| None                                     \|
11:43:53 | game | \| UCHIJAAAA \| sleepingoverhaul   \| 0.1.2         \| Sleeping-Overhaul-Mod-1.12.2.jar            \| d3974446c00f9f1d275edce305771eeddf30c658 \|
11:43:53 | game | \| UCHIJAAAA \| wearablebackpacks  \| 3.1.0         \| Wearable-Backpacks-Mod-1.12.2.jar           \| None                                     \|
11:43:53 | game | \| UCHIJAAAA \| cgm                \| 0.2.1         \| Working-Gun-Mod-1.12.2.jar                  \| None                                     \|
11:43:53 | game | \| UCHIJAAAA \| passableleaves     \| 2.0.0         \| Passable-Leaves-Mod-1.12.2.jar              \| None                                     \|
11:43:53 | game |  
11:43:53 | game | Loaded coremods (and transformers):
11:43:53 | game | PassableLeavesCore (PassableLeavesCore-1.12.2-1.0.0.jar)
11:43:53 | game | teamrtg.passableleaves.asm.PassableLeavesTransformer
11:43:53 | game | TickrateChanger (TickrateChanger-Mod-1.12.2.jar)
11:43:53 | game | me.guichaguri.tickratechanger.TickrateTransformer
11:43:53 | game | ObfuscatePlugin (obfuscate-0.2.4-1.12.2.jar)
11:43:53 | game | com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
11:43:53 | game | CosmicLibFakeCoreMod (CosmicLib-1.12.2-0.3.3.ALPHA.jar)
11:43:53 | game |  
11:43:53 | game | GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
11:43:53 | game | Profiler Position: N/A (disabled)
11:43:53 | game | Player Count: 2 / 8; [EntityPlayerMP['epicninja532'/316, l='Ocean Man', x=-574.70, y=62.00, z=-144.45], EntityPlayerMP['coolguy3484'/1115, l='Ocean Man', x=-46.11, y=65.31, z=177.87]]
11:43:53 | game | Type: Integrated Server (map_client.txt)
11:43:53 | game | Is Modded: Definitely; Client brand changed to 'fml,forge'
11:43:53 | game | [16:43:53] [main/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\Kids\AppData\Roaming\.minecraft\crash-reports\crash-2018-07-14_16.43.53-server.txt
11:43:53 | game | [16:43:53] [main/INFO] [FML]: Waiting for the server to terminate/save.
11:43:53 | game | [16:43:53] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving worlds
11:43:53 | game | [16:43:53] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving chunks for level 'Ocean Man'/overworld
11:43:53 | game | [16:43:53] [Netty Local Client IO #0/INFO] [Tickrate Changer]: Updating server tickrate to 20.0
11:43:53 | game | [16:43:53] [Netty Local Client IO #0/INFO] [Tickrate Changer]: Updating client tickrate to 20.0
11:43:53 | game | [16:43:53] [Server thread/INFO] [FML]: Unloading dimension 0
11:43:53 | game | [16:43:53] [Server thread/INFO] [FML]: Applying holder lookups
11:43:53 | game | [16:43:53] [Server thread/INFO] [FML]: Holder lookups applied
11:43:53 | game | [16:43:53] [Server thread/INFO] [FML]: The state engine was in incorrect state SERVER_STOPPING and forced into state SERVER_STOPPED. Errors may have been discarded.
11:43:53 | game | [16:43:53] [main/INFO] [FML]: Server terminated.

**Comment by TheXFactor117** [comment]
Might not be caused by LSC

> at ru.radviger.cases.item.ItemCase.ofRandomType(ItemCase.java:141)

Does the bug only happen when LSC is installed? Does it happen if you remove the mod mentioned above?

**Comment by LustrousBlue** [comment]
Im not sure which mod that is, but I tried it with just LSC and it still happened, just less frequently

**Comment by LustrousBlue** [comment]
I looked up 141 as a item ID and its carrots? Im not sure if that helps but ill put it here anyway

**Comment by LustrousBlue** [comment]
if possible could you see what mod you might think it is, because I'm not very good with what most of this means, I hope I'm not asking too much

**Comment by LustrousBlue** [comment]
It is not LSC, sorry for the inconvienience, Im trying to find what mod it is

**Comment by TheXFactor117** [comment]
No problem ;)
